# WhatATheme
markdown: kramdown

# URL of the Site
url:
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: '/jekyll'

# Title of the Site
title: Mikoto Studio
# Description of the Site
description: Conceptual 3D Environment in Photo Realistic Quality.
# URL of Image of the Site
site-image: assets/images/catscleinto3d.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: assets/images/logo.svg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: assets/images/gate.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mikoto@mikotostudio.com
facebook_username: 
twitter_username: 
instagram_username: mikotostudio
linkedin_username: mikotostudio
github_username:  mikotostudio
youtube_channel_id: 
reddit_username: 
behance_username: mikotostudio
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: mikotostudio
# URL for the Image of the Author
author-image: assets/images/logo.png
# 60 Words About the Author
author-about: Conceptual 3D Environment Artist in Photo Realistic Quality.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://mikotostudio.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
